version: '2.1'

services:
  moodle-mariadb:
    restart: always
    environment:
      MARIADB_DATABASE: moodledb
      MARIADB_USER: moodleuser
      MARIADB_PASSWORD: hH_="N%.k6&]wTk
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - moodle_mariadb:/var/lib/mysql
    image: mariadb:10.5

  moodle:
    restart: always
    environment:
      DEVICE_HOSTNAME: 0.0.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - moodle_data:/app/moodledata

volumes:
  moodle_data:
  moodle_mariadb:
